### PR TITLE
Aquarium: Remove unused debug overlay

### PR DESCRIPTION
**Pull request by hujiajie**

### CODE REVIEW

**Comment by hujiajie** [comment]
Open: how to merge PRs? Create a merge commit (so no linear history)? Squash and merge? Rebase and merge?

**Comment by shaoboyan** [comment]
I don't think we need to remove them right now. I think these debug functions are useful (during the iteration). If we could move it to debug_utils. or other places, it would be better.

**Comment by hujiajie** [comment]
sudo rm

**Comment by shaoboyan** [comment]
> sudo rm

Then LGTM

**Comment by hujiajie** [comment]
I cannot tell if "Squash and merge" is better than "Rebase and merge" or vice versa, so I did a "Fast-forward and merge". A big win of "Fast-forward and merge" is that it does not re-write the commit at all and therefore GPG signing will be preserved (though I'm not signing my commit here). Unfortunately, "Fast-forward and merge" is a long-requested-but-still-missing feature in GitHub UI, so I have to manually fetch and push via command line.

**Comment by shaoboyan** [comment]
Ack

**Pull request merged**
